### ISSUE TITLE
Unable to use CreateorAlter 

### ISSUE THREAD

**Issue by dmaloo** [microsoft/sqlmanagementobjects#11]
Hi, am trying to write some powershell to script out sql server objects - my code is as below
$scriptr = new-object ('Microsoft.SqlServer.Management.Smo.Scripter') ($SMOserver)

 foreach ($ScriptThis in $DatabaseObjects | Where-Object { $_.schema -eq $schemaname  -and -not $_.IsSystemObject}) {
                        $scriptr = new-object ('Microsoft.SqlServer.Management.Smo.Scripter') ($SMOserver)
                        $scriptr.Options.AppendToFile = $False
                        $scriptr.Options.ScriptSchema = $True
                        $scriptr.Options.AllowSystemObjects = $False
                        $scriptr.Options.ClusteredIndexes = $True
                        $scriptr.Options.DriAllConstraints = $True
                        $scriptr.Options.ScriptDrops = $False
                        $scriptr.Options.IncludeIfNotExists = $False
                        $scriptr.Options.IncludeHeaders = $False
                        $scriptr.Options.ToFileOnly = $True
                        $scriptr.Options.Indexes = $True
                        $scriptr.Options.Permissions = $False
                        $scriptr.Options.WithDependencies = $False
                        $scriptr.Options.IncludeDatabaseContext = $True
                        $scriptr.Options.Triggers = $True
                        $scriptr.Options.EnforceScriptingOptions = $True....

How do I specify 'create or alter' here? If I say $scriptr.Options.CreateorAlter = $true i get an error. I have to do all sorts of manipulations to change generated script to use create or alter, thanks.

**Comment by shueybubbles** [comment]
I think there was an oversight, and CreateOrAlter didn't get hooked up in Scripter.
You can use ScriptMaker directly.
Something like this (translate to powershell)
```C#
                    
var scriptMaker = new ScriptMaker(server);
scriptMaker.Preferences.Behavior = ScriptBehavior.CreateOrAlter;
var stringCollection = scriptMaker.Script(new[] {somesmoobject1, somsmoobject2});
```

Scripter does a bunch of other stuff like handle scripting errors and write to files etc, so if you need that stuff we'd need to hook this up either in ScriptingOptions or in Scripter itself.

**Comment by dmaloo** [comment]
Yes, I do need to write to files and do various other things so i'd rather not switch now. Appreciate if you can fix scripter to do  this also, will use workarounds as of now, thanks.

**Comment by shueybubbles** [comment]
@dmaloo only certain object types support Create Or Alter syntax. You'll need to be careful to only use this setting for those types of objects.

**Comment by shueybubbles** [comment]
@dmaloo  OK I can make CreateOrAlter work for a list of mixed objects, where some implement ICreateOrAlter and some do not. However, it generates a script that on the surface doesn't make much sense - you end up with Tables being created with "CREATE" and sprocs/triggers etc with "CREATE OR ALTER". Such a mix isn't very helpful when scripting an entire database nor when trying to modify an existing database. 

The other `ScriptingOptions` flag that produces a script that's useful for both new and existing databases is `IncludeIfNotExists`.  The main negative behavior of that flag, afaict, is that it ends up using dynamic SQL in its implementation. Is that why you are interested in switching to CREATE OR ALTER?  Or does CREATE OR ALTER have some other behavior that is compelling?

Is it fair to say that the ideal script would be a mix of `if not exists` for objects that don't support createoralter and `create or alter` for types that do? If so I can think of 3 ways to do it, and I'd like feedback from the community.

Option 1 - Change the meaning of `ScriptingOptions.IncludeIfNotExists` such that for objects that support `CREATE OR ALTER` on sql2016 cu1+ it will always use `CREATE OR ALTER`. 

Option 2 - Add a boolean property `ScriptingOptions.ScriptForCreateOrAlter`. When scripting objects that don't support `CREATE OR ALTER` , the value of `ScriptingOptions.IncludeIfNotExists` will be used to determine whether to include the if not exists.

Option 3 - Similar to option 2, but it would ignore the value of `ScriptingOptions.IncludeIfNotExists` and always include `if not exists` for non-createoralterable objects.

**Comment by dmaloo** [comment]
Hi David, Tables are not code. Tables should not absolutely have any create or alter options at any time. Tables should always have drop if exists (if needed with greatest caution, not known a lot of cases for that) and Create only. Code, including triggers needs create or alter.

**Comment by shueybubbles** [comment]
I think I wasn't clear enough in my question. 
`Scripter.EnumScript` accepts an array of objects or URNs. It's possible those objects are a mix of tables/views/sprocs/triggers etc. ScriptingOptions only has a few variables we can set to control the behavior, and those options are used uniformly across all object types today.
Introducing "create or alter" at the Scripter level means that now we have to decide how to treat that option for objects that don't support create or alter. The easiest option is just to fail if the object list includes such objects as Tables. However, I'm guessing heterogeneous lists are common, so I suspect devs would want some rational behavior.  I am leaving `ScriptingOptions.ScriptForCreateDrop` out of the discussion, because forcefully dropping and recreating all objects is a different semantic than create or alter. But we could choose to just change the interpretation of `ScriptingOptions.IncludeIfNotExists` such that sprocs and triggers and the like use CREATE OR ALTER when supported, instead of adding a new property. 

Does that make my question clearer?

**Comment by SteveWithAQ** [comment]
Respectfully disagree on tables should never have create or alter. Sure SQL Server doesn't support that syntax now, but there's no inherent reason why that syntax couldn't be added later. DROP IF EXIST + CREATE (or just a CREATE that fails due to object existence) would both be more dangerous than CREATE OR ALTER on a table if available.

Option 1 is dangerous because there are cases where you want IncludeIfNotExists to result in NOT changing the object - in fact, that's the intuitive effect of that option.

Option 2 makes the most sense to me as it's explicit behavior (i.e, requiring the developer to explicitly set both options and following their explicit instruction.)

Option 3 seems dangerous because there's an assumption on the code that the developer wants that IF NOT EXISTS. They should always have the choice to not include that.

**Comment by shueybubbles** [comment]
good points. I find IncludeIfNotExists=true to be a problematic setting anyway. Consider that you are generating scripts from a source database which is presumably in a coherent state, and now you are going to run those scripts against some target. For every object in the source database, it won't try to overwrite a similarly named object in the destination. But there's absolutely no guarantee that skipping those objects will leave the target in a coherent state and at some point creates will fail because they refer to missing columns etc.  So why did you include those objects in the list of things to script if you don't want them to exist that way on the target for certain? You have to be very careful in which sets of objects you generate scripts for with that set.

**Comment by shueybubbles** [comment]
And I think I missed the boat in `ScriptForCreateDrop` vs `IncludeIfNotExists`. `ScriptForCreateOrAlter` is closer to the former, as it means "make the object like this every time" but it's a lot safer. My bad.

So having an explicit new flag for objects that support it should be the way to go, and have non-createoralter-able objects just follow the old behavior.

The good (?) news is there aren't very many objects in sql server that support create or alter, so fixing up the code shouldn't be too hard. There's a limited amount of polymorphism in the implementation such that there are special cases to deal with.

**Comment by shueybubbles** [comment]
Here's a first pass at a doc:
```
        /// <summary>
        /// Scripts object using "CREATE OR ALTER" syntax. 
        /// </summary>
        /// <remarks>
        /// This setting is not supported for all object types, and only works when the destination is SQL Server 2016 sp1+.
        /// If toggled from true to false, the script behavior will change to CREATE for all objects.
        /// When set to true:
        /// 1. Objects that do not support "CREATE OR ALTER" will be scripted as CREATE. 
        ///    Their script content will depend on ScriptForCreateDrop and IncludeIfNotExists properties.
        /// 2. Objects that support "CREATE OR ALTER" will ignore the ScriptForCreateDrop and IncludeIfNotExists properties.
        /// </remarks>
        public bool ScriptForCreateOrAlter
```

**Comment by shueybubbles** [comment]
Heh I learn something new every day. I find that `ScriptingOptions.ScriptForCreateDrop` is NOT how SSMS implements the "Script as DROP And CREATE" menu item. It uses `ScriptMaker` with a `ScriptingPreferences.Behavior` value set to `ScriptBehavior.DropAndCreate` instead. 
ScriptMaker does all the DROPping separately before scripting the creates:
```
//call create/drop
            if (this.Preferences.Behavior == ScriptBehavior.Drop || this.Preferences.Behavior == ScriptBehavior.DropAndCreate)
            {
                List<Urn> reversedUrns = new List<Urn>(orderedUrns);
                reversedUrns.Reverse();

                this.ScriptDropObjects(reversedUrns);
            }
```

So this setter seems not to be very useful. A quick test app shows a failure:
```
var table = db.CreateTable("tbl");
var options = new ScriptingOptions(db)
{
   ScriptForCreateDrop = true
};
var script = table.Script(options).ToSingleString();
Assert.That(script, Does.Contain("DROP"), "Script with ScriptForCreateDrop");

    Test 'Table_ScriptCreate_respects_ScriptForCreateDrop' failed when targeting server redacted. Message:
      Script with ScriptForCreateDrop
      Expected: String containing "DROP"
      But was:  "SET ANSI_NULLS ON
    SET QUOTED_IDENTIFIER ON
    CREATE TABLE [dbo].[tbl'']]]]]]'{659883e8-81e3-4ea9-935a-3c24db94f327}](
    	[col_1] [int] NULL
    ) ON [PRIMARY]
```

**Comment by shueybubbles** [comment]
@dmaloo  try it out with the latest preview https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/161.41981.14-msdata
