### ISSUE TITLE
Expose OwnerLoginName as a settable property for JobSchedule objects

### ISSUE THREAD

**Issue by ben-thul** [microsoft/sqlmanagementobjects#120]
While having a discussion in the context of "what happens when the owner of a job schedule is no longer a valid login?", I discovered that the Microsoft.SqlServer.Management.Smo.Agent.JobServer class doesn't have an OwnerLoginName property in the same way that the Job class (same namespace) does. By having this as a settable property, it would allow administrators to set the ownership of a job schedule and prevent potential mishaps.

As a means to set it, `sp_update_job` already has a `@owner_login_name` parameter so this feature request is to plumb that into the JobSchedule SMO object.

Thanks in advance.

**Comment by shueybubbles** [comment]
@ben-thul  How do we query the current value of the schedule owner? The docs for `sp_help_schedule` and `sp_help_job_schedule` don't mention owner login.

SMO doesn't have many write-only properties. If we add this capability, and there's no way to read the current owner, it'd probably be a method on `JobSchedule` instead of a property.

**Comment by shueybubbles** [comment]
I guess we can get the sid from here `msdb.dbo.sysschedules_localserver_view` and convert it to a name.

**Comment by ben-thul** [comment]
Sorry if I was unclear - suggesting that it be a writable property wasn't meant to mean "write-only" but "read/write" (contrasting with "read-only").

As to how, either as  you suggest or adding that value as an output to `sp_help_schedule` from whence you can consume it.
