### ISSUE TITLE
root directory for SQL on Linux returned as c:/

### ISSUE THREAD

**Issue by dzsquared** [microsoft/sqlmanagementobjects#146]
appears in https://github.com/microsoft/azuredatastudio/issues/23657 via sqltoolservice

**Comment by shueybubbles** [comment]
SSMS hides root directory for Linux because the path is fixed.

The C:\ value comes from the engine because they never provided a real API to get it. The PAL hosting the engine virtualizes a Windows registry.

This is how SMO gets root directory

        declare @SmoRoot nvarchar(512)
        exec master.dbo.xp_instance_regread N'HKEY_LOCAL_MACHINE', N'SOFTWARE\Microsoft\MSSQLServer\Setup', N'SQLPath', @SmoRoot OUTPUT
     select @smoroot

On Linux you get C:\
![image](https://github.com/microsoft/sqlmanagementobjects/assets/2224906/80fa101a-60aa-4ea8-b62d-cd98b64509f3)
