### ISSUE TITLE
Unable to find SMO to manage contained Availability Groups in SQL Server 2022

### ISSUE THREAD

**Issue by jbrownb** [microsoft/sqlmanagementobjects#154]
From this document, we cannot find anything regarding contained AGs https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo?view=sql-smo-160

**Comment by shueybubbles** [comment]
Are you expecting to find some new functionality for contained AGs besides new properties like `AvailabilityGroup.ReuseSystemDatabases` and `AvailabilityGroup.IsContained`?  The docs definitely need an update.

**Comment by jbrownb** [comment]
This is for a customer of mine. They use Powershell SMO for automation of SQL server AG deployments and management. So they want to know what they can do with the SMO for contained AGs and if the document is going to be updated.

**Comment by Matteo-T** [comment]
Hey @jbrownb - to add to what @shueybubbles wrote abote, here are my comments.

- If the issue is about SMO documentation, then David already told you that the (lacoin and often not very useful, IMHO) SMO documentation is in need of a refresh to at least mention the new stuff added "recently". I  believe he started an e/mail thread with the LEARN folks on how to get that done.

- If the issue is about either SQLPS (legacy PS module user by SQL Agent and hardly updated) or SQLSERVER (new and maintained PS module), then I want to know more about it. The part that throws me off is when you say "PowerShell SMO". Do you mean "programming .Net using using SMO from PowerShell"? The short answer is that they can essentually do few things, just like:

  - Create a new AG (it would be just silly because they would be reimplementing the -ReuseSystemDatabases amd -ContainedAvailabilityGroup I added to the New-SqlAvailabilityGroup cmdlet in the SQLServer module)
  - Inspect the value of the property "IsContained" on the AvailabilityGroup object

Let me know if that's enough for you or provide more info.

**Comment by jbrownb** [comment]
Hello @Matteo-T and @shueybubbles, thanks for the follow up on this one.
I've contacted my customer to get more details on what they are expecting to get specifically. I will confirm once I get their response.

**Comment by jbrownb** [comment]
I got an update from my customer and this is what they are looking for:

We are exploring the use of contained availability groups in our environment. We currently use PowerShell SMO to create and manage traditional availability groups. We would like to be able to use SMO to create contained availability groups with the option of reusing system databases.

A snippet of what we currently do to create traditional availability groups using the AvailabilityGroup class:

$AvailabilityGroup = New-Object Microsoft.SqlServer.Management.Smo.AvailabilityGroup($Server, $AvailabilityGroupName)
foreach($ReplicaHost in $ReplicaHosts)
{
       $AvailabilityReplica = New-Object Microsoft.SqlServer.Management.Smo.AvailabilityReplica($AvailabilityGroup, $ReplicaHost)
       $ReplicaHostFQDN = (Get-ADComputer -Identity $ReplicaHost).DNSHostName
       $AvailabilityReplica.EndpointUrl = "TCP://$($ReplicaHostFQDN):$($EndpointPort)"
       $AvailabilityReplica.FailoverMode = [Microsoft.SqlServer.Management.Smo.AvailabilityReplicaFailoverMode]::$FailoverMode
       $AvailabilityReplica.AvailabilityMode = [Microsoft.SqlServer.Management.Smo.AvailabilityReplicaAvailabilityMode]::$AvailabilityMode
       $AvailabilityGroup.AvailabilityReplicas.Add($AvailabilityReplica)
}
$AvailabilityGroup.Create()

For contained availability groups would we be using a new class, or would It be based on the original class with a new property to distinguish the type of availability group?

**Comment by shueybubbles** [comment]
please reference the change log here 
https://github.com/microsoft/sqlmanagementobjects/blob/3ae2731330f852c8ddc9ab670c6b18cf336d43ab/CHANGELOG.md?plain=1#L57

**Comment by jbrownb** [comment]
Thanks, I'll share that with them
