### ISSUE TITLE
Missing regular property Identity property bag state Lazy for type Column

### ISSUE THREAD

**Issue by ssinfod** [microsoft/sqlmanagementobjects#38]
Hello, 

I'm using SMO NuGet library to find the Identity column in all tables in my database. 
I'm using this NuGet package: Microsoft.SqlServer.SqlManagementObjects 160.2004021.0

For some reason, I got the following message in the "Ouput" window:

BdCleaner.exe Information: 0 : 2020-12-02T08:47:33.7430053-05:00 - get data for urn: Server[@Name='PCNAME-01\DEV']/Database[@Name='MyDatabase']/Table[@Name='MyTable' and @Schema='dbo']/Column[@Name='MyColumn']
BdCleaner.exe Information: 0 : 2020-12-02T08:47:33.7740069-05:00 - Missing regular property Identity property bag state Lazy for type Column

It seems there is something wrong while reading the Identity property. (Missing regular property Identity property bag state Lazy for type Column)
This message is very frequent. In fact, the message seems to happens on **all** columns **except** the one which have Identity.

I'm pretty sure this message was not present in previous version.
I also tried to installed the latest version of the package but I had problems with missing x64 dll.

Any idea what could be wrong with the "Missing regular property" ? 
Is it just a warning that I can Ignore ?

Thanks for your time.

**Comment by shueybubbles** [comment]
Hi @ssinfod 
Recent SMO builds are more verbose in tracing than previous versions would have been. I assume your "bdcleaner.exe" installs a trace listener of some sort so it's picking up these traces.

This particular trace indicates that your code populated Table.Columns without first calling Server.SetDefaultInitFields or without using Columns.ClearAndInitialize and including "Identity" in the property list to fetch. As a result, SMO has to run a query for each Column to populate Identity and whatever other properties were not fetched in the collection construction.

I recommend looking at https://github.com/microsoft/sql-server-samples/blob/master/samples/features/sql-management-objects/src/CollectionSamples.cs for some ideas on optimizing your code performance with SMO. 

If you are having issues working with the new package, please open an issue appropriately. Note that the 161 major version now depends on Microsoft.Data.SqlClient which has its own web of dependencies including a native SNI dll that you'll need to install. If you are using packages.config instead of PackageReference to build your app you'll need to get the appropriate SNI dll from Microsoft.Data.SqlClient.Sni package.

**Comment by ssinfod** [comment]
You are right. 
I'm not calling these methods (SetDefaultInitFields and ClearAndInitialize). I will change my code to call it.

For your info:
I didn't install any trace listener. The message was in the output window. 
I'm simply reading the "Identity" property with SMO. Here is my code:

```
Server server = new Server(new ServerConnection(sqlConnectionSmo));
Table table = server.Databases[bdName].Tables[tableName, schemaName];
string tableFullName = bdName + "." + schemaName + "." + tableName;
if (table != null)
{	
	bool hasIdentify = false;
	foreach (Column c in table.Columns)
	{
		if (c.Identity == true)
		{
			string columnName = c.Name;
			string primaryKey = Convert.ToInt32(c.InPrimaryKey).ToString();
			string dataType = c.DataType.ToString();
			string identity = Convert.ToInt32(c.Identity).ToString();
			hasIdentify = true;
			break;
		}
	}

	if (hasIdentify == true)
	{
		string sqlCmd1 = string.Format("DBCC CHECKIDENT('{0}', RESEED, {1})", tableFullName, newIdSeed);
		server.ConnectionContext.ExecuteNonQuery(sqlCmd1);
	}

// ... more code...

}
```

Indeed, I saw that the 161 major version is now using **Microsoft**.Data.SqlClient
I will retry to update my package with NuGet in a near future.

Thanks for your response. I think you can close this issue.

Greetings,

**Comment by shueybubbles** [comment]
You can query just for the identity column using something like this

table.Columns.ClearAndInitialize(“[@Identity = ‘1’]”, new[] {“Name”, “InPrimaryKey”, “DataType”, “Identity”})

(fix my mail program’s quotes)

Then the Columns collection will only contain identity columns and those properties will all be populated in one query.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ssinfod** [comment]
Cool. thanks !
