### ISSUE TITLE
ServerConnection constuctor signature mismatch issue

### ISSUE THREAD

**Issue by shandysawyer** [microsoft/sqlmanagementobjects#66]
When I try to do this:
```
var connectionString = "xxxx"; 
var sqlConnection = new SqlConnection(connectionString);
var serverConnection = new ServerConnection(sqlConnection);
var server = new Server(serverConnection);
```

The compiler gives me an error for line 3 stating that "Cannot convert from 'System.Data.SqlClient.SqlConnection' to 'Microsoft.SqlServer.Management.Common.IRenewableToken'. This is strange because one of the constructor signatures for ServerConnection is:
```
ServerConnection(System.Data.SqlClient.SqlConnection sqlConnection)
```

Very confused why the compiler cant match them up. I'm guessing ServerConnection isn't under your domain since its in a different namespace? Is there another way I can use SqlConnection for Server? I ask because the connection may switch between windows authentication and username and password.

**Comment by shueybubbles** [comment]
SMO versions 160+ don’t use System.Data.SqlClient anymore, they use Microsoft.Data.SqlClient

public ServerConnection (Microsoft.Data.SqlClient.SqlConnection sqlConnection);


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Shandy ***@***.***>
Sent: Sunday, August 8, 2021 2:10 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [microsoft/sqlmanagementobjects] ServerConnection constuctor signature mismatch issue (#66)


When I try to do this:

SqlConnection connection = new SqlConnection(connectionString);

ServerConnection serverConnection = new ServerConnection(connection);

var server = new Server(connection);

The compiler gives me an error for line 2 stating that "Cannot convert from 'System.Data.SqlClient.SqlConnection' to 'Microsoft.SqlServer.Management.Common.IRenewableToken'. This is strange because one of the constructor signatures for ServerConnection is:

ServerConnection(System.Data.SqlClient.SqlConnection sqlConnection)

Very confused why the compiler cant match them up. I'm guessing ServerConnection isn't under your domain since its in a different namespace? Is there another way I can use SqlConnection for Server? I ask because the connection may switch between windows authentication and username and password.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fsqlmanagementobjects%2Fissues%2F66&data=04%7C01%7C%7Cca663499956e4f69132a08d95a97daec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640430514072850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RGvSbgIlABMkEcHr8xEsyXwcGLQwqkgQIZrS6ybmfBM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAQ7GCQJYNLQZEZGGJXFPZTT33CCVANCNFSM5BYW6RSQ&data=04%7C01%7C%7Cca663499956e4f69132a08d95a97daec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640430514082844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YhAXBIoykQbgtd%2FH0%2BoWWPq%2FSK8OamM2k8PONAwXG%2BA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cca663499956e4f69132a08d95a97daec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640430514082844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w%2FcLtIn7G%2F9dhmK8eZpPcOp20WTBh3mwWSP6Afi8bag%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cca663499956e4f69132a08d95a97daec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640430514092837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=okSc9paeeE0moZp2w9Kt6MISHM%2Br1WPPIrgqKTb2NR8%3D&reserved=0>.
